#This is a test config file which is correctly formatted, but doesn't contain all the required entries. It's used as a small config sub-set for testing config file parsing, but not for validation of full config files.

flux_calc = rapid

# Sea surface temperature to use (valid options are 'yes' or 'no').
# If only one is enabled the other will be derived according to, i.e.:
# 		sstskin = sstfnd - cool_skin_difference
# Default value for cool_skin_difference is 0.17K (Donlon et al., 2002)
sst_gradients = yes
cool_skin_difference = 0.17
saline_skin_value = 0.1

# Latitude, longitude and time product names (these are taken from the data layer names in
# axes_data_layer, which must contain the name of datalayer defined below, e.g. 'sstskin').
# Typically 'lat' and 'lon' unless using Takahashi which is 'latitude' and 'longitude'.
axes_data_layer = sstskin
latitude_prod = lat
longitude_prod = lon
time_prod = time


# Selected gas transfer velocity (k) parameterisation. Options include:
# k_Ho2006, k_Nightingale2000, kt_OceanFluxGHG, k_Wanninkhof1992, k_Wanninkhof2014,
# k_McGillis2001, k_Ho1997, kd_OceanFluxGHG_backscatter, kd_OceanFluxGHG_wind,
# kb_OceanFluxGHG, kt_OceanFluxGHG_kd_wind, k_generic
k_parameterisation = k_Nightingale2000


#
# Output directory for the resultant netcdf files
#
output_dir = test_output/test_config_output


################ Data layers
# sst skin data inputs
sstskin_path = <FEROOT>/data/verification_data/SST/<YYYY>/<YYYY><MM>01_OCF-SST-GLO-1M-100-ATS-ARC.nc
sstskin_prod = sst_skin_mean

# DJF added - 18/11/2024 - Added min and max bounds for variables as per there reference validation runs - settings.xml has been updated and therefore breaks the verification runs.
sstskinC_maxBound = 100
sstskinC_minBound = -1.8

sstskin_maxBound = 400
sstskin_minBound = 271.35

sstfndC_maxBound = 100
sstfndC_minBound = -1.8

pco2_sst_maxBound = 30.5
pco2_sst_minBound = -1.8

